apiVersion: v1
kind: Service
metadata: 
  name: mysql-service
spec:
  type: ClusterIP
  ports:    
    - protocol: TCP
      targetPort: 80           
      port: 3306
   
  selector:
    app: mysql 
