apiVersion: v1
kind: Service
metadata:
  labels:
    app: wordpress
  name: wordpress-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30009
  selector:
    app: wordpress
